name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-simulation:
    runs-on: self-hosted
    timeout-minutes: 5  # Общий таймаут всего workflow
    if: github.actor != 'github-classroom[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create and activate venv
        run: |
          python -m venv venv
          source venv/bin/activate
          echo "VIRTUAL_ENV=$PWD/venv" >> $GITHUB_ENV
          echo "$PWD/venv/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
        env:
          PIP_PROGRESS_BAR: on  # Показывать прогресс установки участнику

      - name: Run simulation with timeout
        run: |
          source venv/bin/activate
          echo "Starting simulation with parameters: 8000 18000 8001"
          
          # Запуск с таймаутом 3 минуты (180 секунд)
          timeout 180 python main.py 8000 18000 8001 || echo "Simulation timed out after 3 minutes"
          
          # Вывод результатов
          echo "Simulation results:"
          cat /home/user/competition/GSLauncher/installed/v1.3.3/GeoscanSimulator/Results.txt
        env:
          PYTHONUNBUFFERED: 1  # Для немедленного вывода логов